// Display names of the preisgucken.de categories referenced by `pgLink` in
// lib/blogCategories.ts. Used for the keyword anchor text in <RelatedOffers>.
export const PG_CATEGORY_NAMES: Record<string, string> = {
  "kabel-adapter": "Kabel & Adapter",
  "arbeitskleidung-arbeitsschutz": "Arbeitskleidung & Arbeitsschutz",
  "auto-fahrzeugzubehoer": "Auto & Fahrzeugzubehör",
  "baby-ausstattung": "Baby-Ausstattung",
  "baby-world": "Baby World",
  "balkonkraftwerke": "Balkonkraftwerke & Solar",
  "beamer": "Beamer",
  "beschlaege-schloesser": "Beschläge & Schlösser",
  "brautkleider": "Brautkleider",
  "buero-schreibwaren": "Büro & Schreibwaren",
  "damenmode": "Damenmode",
  "e-scooter": "E-Scooter",
  "eierkocher": "Eierkocher",
  "elektroinstallation": "Elektroinstallation",
  "elektronik": "Elektronik",
  "fernseher": "Fernseher",
  "foto-optik": "Foto & Optik",
  "fritteusen-heissluftfritteusen": "Fritteusen & Heißluftfritteusen",
  "gartenmoebel": "Gartenmöbel",
  "gesichtspflege": "Gesichtspflege",
  "gesundheit": "Gesundheit & Pflege",
  "grills-outdoor-kueche": "Grills & Outdoor-Küche",
  "handyhuellen": "Handyhüllen",
  "heimkino": "Heimkino",
  "heizung": "Heizung",
  "herrenmode": "Herrenmode",
  "hoverboards": "Hoverboards",
  "kaffeemaschinen": "Kaffeemaschinen",
  "kaffeevollautomaten": "Kaffeevollautomaten & Kapselmaschinen",
  "kinderwagen-unterwegs": "Kinderwagen & Unterwegs",
  "kinderzimmer": "Kinderzimmer",
  "kleider": "Kleider",
  "kleine-kuechengeraete": "Kleine Küchengeräte",
  "kochplatten-kochfelder": "Kochplatten & Kochfelder",
  "kopfhoerer-lautsprecher": "Kopfhörer & Lautsprecher",
  "kosmetik-beauty": "Kosmetik & Beauty",
  "kueche": "Küche",
  "kuechenmaschinen": "Küchenmaschinen",
  "laptops": "Laptops & Notebooks",
  "laufbaender": "Laufbänder",
  "leuchten": "Leuchten",
  "maehroboter": "Mähroboter",
  "materialbearbeitung": "Materialbearbeitung",
  "mikrowellen": "Mikrowellen",
  "monitore": "Monitore",
  "motorradzubehoer": "Motorradzubehör",
  "nahrungsergaenzung-vitamine": "Nahrungsergänzung & Vitamine",
  "parfuem": "Parfüm",
  "pc-it-zubehoer": "PC & IT-Zubehör",
  "schlafen": "Schlafen",
  "schmuck": "Schmuck",
  "schuhe": "Schuhe",
  "sessel": "Sessel",
  "sitzen": "Sitzen",
  "smart-home-steuerungstechnik": "Smart Home & Steuerungstechnik",
  "smartphones": "Smartphones",
  "smartwatch-armbaender": "Smartwatch-Armbänder",
  "spielzeug": "Spielzeug",
  "sportschuhe": "Sportschuhe",
  "standmixer-puerierstaebe": "Standmixer & Pürierstäbe",
  "suesswaren": "Süßwaren & Schokolade",
  "taschen-koffer": "Taschen & Koffer",
  "tierbedarf": "Tierbedarf",
  "toaster": "Toaster",
  "ueberwachungskameras": "Überwachungskameras",
  "uhren": "Uhren",
  "umstandsmode": "Umstandsmode",
  "vorhaenge": "Vorhänge",
  "wasserkocher": "Wasserkocher",
  "werkzeug-heimwerken": "Werkzeug & Heimwerken",
  "wlan-router-mesh": "WLAN-Router & Mesh-Systeme",
  "wohnaccessoires": "Wohnaccessoires",
};
